/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness + dependency check.
         *
         *     Returns 503 when the database is unreachable so that an uptime monitor, and later
         *     Nginx, can tell "process is running" apart from "process can actually serve requests".
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/works": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Works */
        get: operations["list_works_api_works_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/works/{work_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Work */
        get: operations["get_work_api_works__work_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Books */
        get: operations["list_books_api_books_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Book */
        get: operations["get_book_api_books__book_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Cover
         * @description 404s for every book today — no cover images exist in the source material (per the
         *     project brief: covers are deferred). The endpoint exists now so the client can wire
         *     up the URL and treat 404 as "show a placeholder" from day one.
         */
        get: operations["download_cover_api_books__book_id__cover_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/pages/{sequence}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Book Page
         * @description One page of a book, for reading without downloading it. `sequence` is the page's
         *     position in the book (the `sequence` field of a search hit / of the book JSON), not
         *     its printed label, which is not unique within a book.
         */
        get: operations["get_book_page_api_books__book_id__pages__sequence__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{book_id}/toc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Book Toc */
        get: operations["get_book_toc_api_books__book_id__toc_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/authors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Authors */
        get: operations["list_authors_api_authors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Categories */
        get: operations["list_categories_api_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/libraries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Libraries */
        get: operations["list_libraries_api_libraries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Languages */
        get: operations["list_languages_api_languages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_api_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/toc/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Toc */
        get: operations["search_toc_api_toc_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthorOut */
        AuthorOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Deathlabel */
            deathLabel?: string | null;
        };
        /**
         * BookOut
         * @description One volume — the downloadable unit. Matches CatalogBook in the iOS brief.
         */
        BookOut: {
            /** Bookid */
            bookId: string;
            /** Workid */
            workId: string;
            /** Worktitle */
            workTitle: string;
            /** Volume */
            volume: number | null;
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Authordeath */
            authorDeath: string | null;
            /** Description */
            description: string | null;
            /** Subjects */
            subjects: components["schemas"]["SubjectOut"][];
            /** Libraries */
            libraries: components["schemas"]["LibraryOut"][];
            /** Language */
            language: string | null;
            /** Publisher */
            publisher: string | null;
            /** Shamelacollection */
            shamelaCollection: string | null;
            /** Pagefirst */
            pageFirst: number | null;
            /** Pagelast */
            pageLast: number | null;
            /** Paragraphcount */
            paragraphCount: number | null;
            /** Sizebytes */
            sizeBytes: number;
            /** Downloadbytes */
            downloadBytes: number;
            /** Contentversion */
            contentVersion: number;
        };
        /**
         * CategoryOut
         * @description An item of GET /api/categories: a subject plus its position in the list, so the
         *     server -- not the app -- decides where a new category sits. Deliberately not part of
         *     SubjectOut, which is embedded in every book and work.
         */
        CategoryOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Order */
            order: number;
            /** Section */
            section: string;
            /**
             * Pinnedbookids
             * @default []
             */
            pinnedBookIds: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Response for GET /api/health.
         *
         *     `status` is "ok" only when every dependency the API needs to serve real traffic is
         *     actually reachable — a health check that returns 200 while the database is down is
         *     worse than no health check, because it's what a VPS load balancer or an uptime
         *     monitor will trust.
         */
        HealthResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
            /**
             * Database
             * @enum {string}
             */
            database: "up" | "down";
            /** Books Root Present */
            books_root_present: boolean;
            /** Covers Root Present */
            covers_root_present: boolean;
        };
        /** LanguageOut */
        LanguageOut: {
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
        /**
         * LibraryOut
         * @description A curated grouping (see app.models.library.Library) -- independent of `subjects`.
         *     Open-ended and admin-creatable, unlike the fixed 39 subjects. `parentId` supports
         *     optional nesting; a flat list (not a tree) is returned from GET /api/libraries, the
         *     same choice already made for subjects -- the client groups by parentId itself.
         */
        LibraryOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Parentid */
            parentId?: string | null;
        };
        /** PageEnvelope[BookOut] */
        PageEnvelope_BookOut_: {
            /** Page */
            page: number;
            /** Limit */
            limit: number;
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["BookOut"][];
        };
        /** PageEnvelope[SearchHit] */
        PageEnvelope_SearchHit_: {
            /** Page */
            page: number;
            /** Limit */
            limit: number;
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["SearchHit"][];
        };
        /** PageEnvelope[WorkOut] */
        PageEnvelope_WorkOut_: {
            /** Page */
            page: number;
            /** Limit */
            limit: number;
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["WorkOut"][];
        };
        /** PageResponse */
        PageResponse: {
            /** Bookid */
            bookId: string;
            /** Contentversion */
            contentVersion: number;
            /** Pagecount */
            pageCount: number;
            /** Page */
            page: {
                [key: string]: unknown;
            };
            /** Sectiontitle */
            sectionTitle: string | null;
            /** Prevsequence */
            prevSequence: number | null;
            /** Nextsequence */
            nextSequence: number | null;
        };
        /** SearchHit */
        SearchHit: {
            /** Bookid */
            bookId: string;
            /** Workid */
            workId: string;
            /** Worktitle */
            workTitle: string;
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Volume */
            volume: number | null;
            /** Subjects */
            subjects: components["schemas"]["SubjectOut"][];
            /** Libraries */
            libraries: components["schemas"]["LibraryOut"][];
            /** Sectiontitle */
            sectionTitle: string | null;
            /** Page */
            page: string;
            /** Pagesequence */
            pageSequence: number;
            /** Snippet */
            snippet: string;
            /** Matchstart */
            matchStart: number | null;
            /** Matchend */
            matchEnd: number | null;
            /** Score */
            score: number;
        };
        /** SubjectOut */
        SubjectOut: {
            /** Id */
            id: string;
            /** Title */
            title: string;
        };
        /** TocEntryOut */
        TocEntryOut: {
            /** Id */
            id: string;
            /** Order */
            order: number;
            /** Title */
            title: string;
            /** Pagesequence */
            pageSequence: number | null;
            /** Pagenumber */
            pageNumber: string | null;
        };
        /**
         * TocHit
         * @description One chapter heading matched by GET /api/toc/search. Field names follow SearchHit
         *     (bookId/workId as strings, page + pageSequence) so the client's decoding carries over;
         *     the sequence is what GET /api/books/{id}/pages/{sequence} and the downloaded JSON's
         *     pages are keyed by, the label is only what is printed.
         */
        TocHit: {
            /** Bookid */
            bookId: string;
            /** Workid */
            workId: string;
            /** Worktitle */
            workTitle: string;
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Volume */
            volume: number | null;
            /** Heading */
            heading: string;
            /** Tocid */
            tocId: string;
            /** Order */
            order: number;
            /** Page */
            page: string;
            /** Pagesequence */
            pageSequence: number | null;
        };
        /** TocResponse */
        TocResponse: {
            /** Bookid */
            bookId: string;
            /** Contentversion */
            contentVersion: number;
            /** Pagecount */
            pageCount: number;
            /** Entries */
            entries: components["schemas"]["TocEntryOut"][];
        };
        /** TocSearchResponse */
        TocSearchResponse: {
            /** Page */
            page: number;
            /** Limit */
            limit: number;
            /** Total */
            total: number;
            /** Items */
            items: components["schemas"]["TocHit"][];
            /** Capped */
            capped: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WorkDetailOut
         * @description GET /api/works/{workId}: the summary plus every volume, per Amendment 2 —
         *     volumes are deliberately NOT embedded in the list endpoint's WorkOut.
         */
        WorkDetailOut: {
            /** Workid */
            workId: string;
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Authordeath */
            authorDeath: string | null;
            /** Subjects */
            subjects: components["schemas"]["SubjectOut"][];
            /** Libraries */
            libraries: components["schemas"]["LibraryOut"][];
            /** Language */
            language: string | null;
            /** Volumecount */
            volumeCount: number;
            /** Totalsizebytes */
            totalSizeBytes: number;
            /** Shamelacollection */
            shamelaCollection: string | null;
            /** Isfeatured */
            isFeatured: boolean;
            /** Volumes */
            volumes: components["schemas"]["BookOut"][];
        };
        /**
         * WorkOut
         * @description One title, independent of volume count. Matches CatalogWork in Amendment 2.
         */
        WorkOut: {
            /** Workid */
            workId: string;
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Authordeath */
            authorDeath: string | null;
            /** Subjects */
            subjects: components["schemas"]["SubjectOut"][];
            /** Libraries */
            libraries: components["schemas"]["LibraryOut"][];
            /** Language */
            language: string | null;
            /** Volumecount */
            volumeCount: number;
            /** Totalsizebytes */
            totalSizeBytes: number;
            /** Shamelacollection */
            shamelaCollection: string | null;
            /** Isfeatured */
            isFeatured: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_works_api_works_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                subject?: string | null;
                library?: number | null;
                language?: string | null;
                author?: number | null;
                featured?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageEnvelope_WorkOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_work_api_works__work_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                work_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_books_api_books_get: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                subject?: string | null;
                library?: number | null;
                language?: string | null;
                author?: number | null;
                work?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageEnvelope_BookOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_book_api_books__book_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_cover_api_books__book_id__cover_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_book_page_api_books__book_id__pages__sequence__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
                sequence: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_book_toc_api_books__book_id__toc_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TocResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_authors_api_authors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorOut"][];
                };
            };
        };
    };
    list_categories_api_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryOut"][];
                };
            };
        };
    };
    list_libraries_api_libraries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryOut"][];
                };
            };
        };
    };
    list_languages_api_languages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LanguageOut"][];
                };
            };
        };
    };
    search_api_search_get: {
        parameters: {
            query: {
                /** @description Arabic search query */
                q: string;
                page?: number;
                limit?: number;
                /** @description One or more subject category IDs */
                subject?: string[] | null;
                /** @description One or more library IDs */
                library?: number[] | null;
                /** @description One or more language codes */
                language?: string[] | null;
                /** @description One or more author IDs */
                author?: number[] | null;
                /** @description One or more author names (use when the ID isn't known) */
                authorName?: string[] | null;
                /** @description One or more work IDs */
                work?: number[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageEnvelope_SearchHit_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_toc_api_toc_search_get: {
        parameters: {
            query: {
                /** @description Heading text; sent as typed, folded server-side */
                q: string;
                page?: number;
                limit?: number;
                /** @description One or more subject category IDs */
                subject?: string[] | null;
                /** @description One or more library IDs */
                library?: number[] | null;
                /** @description One or more language codes */
                language?: string[] | null;
                /** @description One or more author IDs */
                author?: number[] | null;
                /** @description One or more author names */
                authorName?: string[] | null;
                /** @description One or more work IDs */
                work?: number[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TocSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
